### ISSUE TITLE
Add Learn to apply button click to dataLayer

### ISSUE THREAD

**Issue by amaria** [usds/questionable#220]
On click of the "Learn to apply" button at the end of the eligibility questionnaire, we need the following click event pushed to the dataLayer ...

{
                event: "click",
                event_category: "click",
                event_name: "learn_how_to_apply_quest",
                event_label: "learn_how_to_apply",
                click_type: "cta",
                link_text: "learn_how_to_apply",
                link_url: "/apply?clickedApply=1" or "/apply" if not survey
}

**Comment by froehlichcr** [comment]
Fixed in 1.1.12
