### ISSUE TITLE
Update designs based on user feedback

### ISSUE THREAD

**Issue by froehlichcr** [usds/questionable#46]
The latest designs are visible at https://projects.invisionapp.com/share/AF114SEF9385#/screens/453052719.

Notable changes include:

- [ ] Create exit modal to confirm before leaving the wizard (refreshing the page) that all changes will be lost if done
- [x] Make card border optional
  - [x] Defaults to off
- [x] Make card title an h3
- [x] Make card subtitle a p
- [x] Make borders around multi-select/choice optional
  - [x] Defaults to on
- [x] Make question info appear below question component in a summary box
- [x] Make next/prev button configurable
  - [x] Option to left align buttons
  - [x] "Go Back" can be above card
  - [x] Default to text link for "Go Back"
  - [x] Allow config to set default text for all prev/next buttons
- [x] Create 2nd progress bar option for no label design beneath the card

**Comment by froehlichcr** [comment]
@laura-carollo I believe this covers everything in your latest designs. My goal is to accomplish all of your new design patterns while still supporting the existing patterns (so it's more configurable), but it will default to the new design.

**Comment by laura-carollo** [comment]
@crfroehlich that covers most of it, a couple additional items: 

For questions: 
- [ ] make card background color optional (white in my layouts, gray in prototype)
- [ ] separate styling for supporting details (teal box) vs. question help (card subtitle p)
- [ ] supporting details should be custom design element: #D5FBF3 background, #1DC2AE 1px border, body (p) text inset with consistent padding all 4 sides

Other pages:
- [ ] Updated styles for the review page (it has placeholder copy but the designs are done)
- [ ] Updated styles for the results page (it has placeholder copy but the designs are done)

I assume these items will be handled by the cms: 

- simplified header when in question flow and results pages
- simplified footer when in question flow and results pages
- colors styles
- decision pending on where results page is built, so noting it here and on to-do's above.

**Comment by laura-carollo** [comment]
Oh andddddd almost forgot @crfroehlich 

- [ ] Check responsive break points for tablet and mobile are adjusting correctly (mobile mockup in invision)
